# Generated by Django 4.0 on 2022-01-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_rename_username_useraccount_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='name',
            new_name='username',
        ),
    ]
