# Generated by Django 4.0 on 2022-02-08 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_rename_name_useraccount_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('access_lynk', models.CharField(max_length=255)),
                ('size', models.IntegerField(default=0)),
                ('path', models.CharField(default='', max_length=255)),
                ('parent', models.CharField(max_length=255)),
                ('childs', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='cloud.useraccount')),
            ],
        ),
    ]
