# Generated by Django 4.0 on 2022-02-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='main_folder',
            field=models.BooleanField(default=False),
        ),
    ]
