# Generated by Django 4.0 on 2022-02-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_useraccount_main_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
