# Generated by Django 4.0 on 2022-02-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0006_alter_file_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='parent',
        ),
        migrations.AddField(
            model_name='file',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
