# Generated by Django 4.0 on 2022-02-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0007_remove_file_parent_file_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filedata',
            field=models.FileField(default='', null=True, upload_to=''),
        ),
    ]
