# Generated by Django 4.0 on 2022-02-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0009_fileupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='filedata',
            new_name='file',
        ),
    ]
